apiVersion: batch/v1
kind: CronJob

metadata:
  name: cronjob-ejemplo

spec:
  schedule: "* * * * *" # Ejecutar cada 2 minutos
  timeZone: "America/Lima" # Configurar la zona horaria a Lima, Perú

  #concurrencyPolicy: Forbid # Evitar que se ejecuten múltiples instancias del mismo cronjob al mismo tiempo
  successfulJobsHistoryLimit: 3 # Limitar la cantidad de jobs exitosos a mantener en el historial
  #failedJobsHistoryLimit: 1 # Limitar la cantidad de jobs fallidos a mantener
  #staringDeadlineSeconds: 30 # Tiempo límite para iniciar un job después de su programación

  jobTemplate:
    spec:
      backoffLimit: 2 # cantidad de reintentos en caso de fallo (failed job retries)

      template:
        spec:
          containers:
          - name: cronjob-ejemplo-container
            image: busybox
            command:
              - sh
              - -c
              - |
                echo "Ejecutando CronJob"
                echo "Hostname: $(hostname)"
                echo "Fecha: $(date)"
                sleep 10
                echo "CronJob finalizado"
          restartPolicy: Never