apiVersion: v1
kind: Pod
metadata:
  name: nginx-secret-file

spec:
  containers:
  - name: nginx-secret
    image: nginx:alpine
    ports:
      - containerPort: 80
    
    volumeMounts:
      - name: secret-volume
        mountPath: "/etc/secrets"
        readOnly: true
  volumes:
    - name: secret-volume
      secret:
        secretName: mysql-secret