apiVersion: v1
kind: Pod

metadata:
  name: nginx-config

spec:
  containers:
    - name: nginx-config
      image: nginx:alpine
      ports:
        - containerPort: 80
      envFrom:
        - configMapRef:
            name: app-config