apiVersion: v1
kind: Pod
metadata:
  name: nginx-secret-segundo

spec:
  containers:
  - name: nginx-secret-segundo
    image: nginx:alpine
    ports:
      - containerPort: 80
    env:
      - name: DB_USERNAME
        valueFrom:
          secretKeyRef:
            name: mysql-secret
            key: username
