apiVersion: v1
kind: Pod
metadata:
  name: nginx-secret

spec:
  containers:
  - name: nginx-secret
    image: nginx:alpine
    ports:
      - containerPort: 80
    envFrom:
      - secretRef:
          name: mysql-secret  
