apiVersion: v1
kind: Secret

metadata:
  name: mysql-secret

type: Opaque

# Forma 1, pasando los valores en formato base64
#data:
#  username: bXlzcWwtdXNlcg==  # base64 encoded value of 'mysql-user'
#  password: cGFzc3dvcmQ=      # base64 encoded value of 'password'

# Forma 2, pasando los valores en texto plano
stringData:
  username: mysql-user
  password: password
